
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Accordion': typeof import("../../front/components/ui/Accordion.vue")['default']
    'Address': typeof import("../../front/components/ui/Address.vue")['default']
    'Button': typeof import("../../front/components/ui/Button.vue")['default']
    'CheckBox': typeof import("../../front/components/ui/CheckBox.vue")['default']
    'Container': typeof import("../../front/components/ui/Container.vue")['default']
    'DatePicker': typeof import("../../front/components/ui/DatePicker.vue")['default']
    'Default': typeof import("../../front/components/ui/Default.vue")['default']
    'DropDown': typeof import("../../front/components/ui/DropDown.vue")['default']
    'Header': typeof import("../../front/components/ui/Header.vue")['default']
    'ImageGalerie': typeof import("../../front/components/ui/ImageGalerie.vue")['default']
    'ImageUploader': typeof import("../../front/components/ui/ImageUploader.vue")['default']
    'InputForm': typeof import("../../front/components/ui/InputForm.vue")['default']
    'InputFormItem': typeof import("../../front/components/ui/InputFormItem.vue")['default']
    'Map': typeof import("../../front/components/ui/Map.vue")['default']
    'Modal': typeof import("../../front/components/ui/Modal.vue")['default']
    'Radio': typeof import("../../front/components/ui/Radio.vue")['default']
    'Table': typeof import("../../front/components/ui/Table.vue")['default']
    'TableContainer': typeof import("../../front/components/ui/TableContainer.vue")['default']
    'TableItem': typeof import("../../front/components/ui/TableItem.vue")['default']
    'Text': typeof import("../../front/components/ui/Text.vue")['default']
    'TextArea': typeof import("../../front/components/ui/TextArea.vue")['default']
    'Tip': typeof import("../../front/components/ui/Tip.vue")['default']
    'AdminInvitationList': typeof import("../../front/components/domain/admin/AdminInvitationList.vue")['default']
    'CustomBankDetails': typeof import("../../front/components/domain/custom/CustomBankDetails.vue")['default']
    'CustomClosings': typeof import("../../front/components/domain/custom/CustomClosings.vue")['default']
    'CustomContact': typeof import("../../front/components/domain/custom/CustomContact.vue")['default']
    'CustomDesign': typeof import("../../front/components/domain/custom/CustomDesign.vue")['default']
    'CustomEventDetails': typeof import("../../front/components/domain/custom/CustomEventDetails.vue")['default']
    'CustomGalerie': typeof import("../../front/components/domain/custom/CustomGalerie.vue")['default']
    'CustomGreetings': typeof import("../../front/components/domain/custom/CustomGreetings.vue")['default']
    'CustomNotice': typeof import("../../front/components/domain/custom/CustomNotice.vue")['default']
    'CustomOrganizers': typeof import("../../front/components/domain/custom/CustomOrganizers.vue")['default']
    'CustomPreview': typeof import("../../front/components/domain/custom/CustomPreview.vue")['default']
    'ViewInvitation': typeof import("../../front/components/domain/view/ViewInvitation.vue")['default']
    'NuxtWelcome': typeof import("../../front/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../front/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../front/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../front/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../../front/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../front/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAccordion': typeof import("../../front/components/ui/Accordion.vue")['default']
    'LazyAddress': typeof import("../../front/components/ui/Address.vue")['default']
    'LazyButton': typeof import("../../front/components/ui/Button.vue")['default']
    'LazyCheckBox': typeof import("../../front/components/ui/CheckBox.vue")['default']
    'LazyContainer': typeof import("../../front/components/ui/Container.vue")['default']
    'LazyDatePicker': typeof import("../../front/components/ui/DatePicker.vue")['default']
    'LazyDefault': typeof import("../../front/components/ui/Default.vue")['default']
    'LazyDropDown': typeof import("../../front/components/ui/DropDown.vue")['default']
    'LazyHeader': typeof import("../../front/components/ui/Header.vue")['default']
    'LazyImageGalerie': typeof import("../../front/components/ui/ImageGalerie.vue")['default']
    'LazyImageUploader': typeof import("../../front/components/ui/ImageUploader.vue")['default']
    'LazyInputForm': typeof import("../../front/components/ui/InputForm.vue")['default']
    'LazyInputFormItem': typeof import("../../front/components/ui/InputFormItem.vue")['default']
    'LazyMap': typeof import("../../front/components/ui/Map.vue")['default']
    'LazyModal': typeof import("../../front/components/ui/Modal.vue")['default']
    'LazyRadio': typeof import("../../front/components/ui/Radio.vue")['default']
    'LazyTable': typeof import("../../front/components/ui/Table.vue")['default']
    'LazyTableContainer': typeof import("../../front/components/ui/TableContainer.vue")['default']
    'LazyTableItem': typeof import("../../front/components/ui/TableItem.vue")['default']
    'LazyText': typeof import("../../front/components/ui/Text.vue")['default']
    'LazyTextArea': typeof import("../../front/components/ui/TextArea.vue")['default']
    'LazyTip': typeof import("../../front/components/ui/Tip.vue")['default']
    'LazyAdminInvitationList': typeof import("../../front/components/domain/admin/AdminInvitationList.vue")['default']
    'LazyCustomBankDetails': typeof import("../../front/components/domain/custom/CustomBankDetails.vue")['default']
    'LazyCustomClosings': typeof import("../../front/components/domain/custom/CustomClosings.vue")['default']
    'LazyCustomContact': typeof import("../../front/components/domain/custom/CustomContact.vue")['default']
    'LazyCustomDesign': typeof import("../../front/components/domain/custom/CustomDesign.vue")['default']
    'LazyCustomEventDetails': typeof import("../../front/components/domain/custom/CustomEventDetails.vue")['default']
    'LazyCustomGalerie': typeof import("../../front/components/domain/custom/CustomGalerie.vue")['default']
    'LazyCustomGreetings': typeof import("../../front/components/domain/custom/CustomGreetings.vue")['default']
    'LazyCustomNotice': typeof import("../../front/components/domain/custom/CustomNotice.vue")['default']
    'LazyCustomOrganizers': typeof import("../../front/components/domain/custom/CustomOrganizers.vue")['default']
    'LazyCustomPreview': typeof import("../../front/components/domain/custom/CustomPreview.vue")['default']
    'LazyViewInvitation': typeof import("../../front/components/domain/view/ViewInvitation.vue")['default']
    'LazyNuxtWelcome': typeof import("../../front/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../front/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../front/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../front/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../../front/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../front/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Accordion: typeof import("../../front/components/ui/Accordion.vue")['default']
export const Address: typeof import("../../front/components/ui/Address.vue")['default']
export const Button: typeof import("../../front/components/ui/Button.vue")['default']
export const CheckBox: typeof import("../../front/components/ui/CheckBox.vue")['default']
export const Container: typeof import("../../front/components/ui/Container.vue")['default']
export const DatePicker: typeof import("../../front/components/ui/DatePicker.vue")['default']
export const Default: typeof import("../../front/components/ui/Default.vue")['default']
export const DropDown: typeof import("../../front/components/ui/DropDown.vue")['default']
export const Header: typeof import("../../front/components/ui/Header.vue")['default']
export const ImageGalerie: typeof import("../../front/components/ui/ImageGalerie.vue")['default']
export const ImageUploader: typeof import("../../front/components/ui/ImageUploader.vue")['default']
export const InputForm: typeof import("../../front/components/ui/InputForm.vue")['default']
export const InputFormItem: typeof import("../../front/components/ui/InputFormItem.vue")['default']
export const Map: typeof import("../../front/components/ui/Map.vue")['default']
export const Modal: typeof import("../../front/components/ui/Modal.vue")['default']
export const Radio: typeof import("../../front/components/ui/Radio.vue")['default']
export const Table: typeof import("../../front/components/ui/Table.vue")['default']
export const TableContainer: typeof import("../../front/components/ui/TableContainer.vue")['default']
export const TableItem: typeof import("../../front/components/ui/TableItem.vue")['default']
export const Text: typeof import("../../front/components/ui/Text.vue")['default']
export const TextArea: typeof import("../../front/components/ui/TextArea.vue")['default']
export const Tip: typeof import("../../front/components/ui/Tip.vue")['default']
export const AdminInvitationList: typeof import("../../front/components/domain/admin/AdminInvitationList.vue")['default']
export const CustomBankDetails: typeof import("../../front/components/domain/custom/CustomBankDetails.vue")['default']
export const CustomClosings: typeof import("../../front/components/domain/custom/CustomClosings.vue")['default']
export const CustomContact: typeof import("../../front/components/domain/custom/CustomContact.vue")['default']
export const CustomDesign: typeof import("../../front/components/domain/custom/CustomDesign.vue")['default']
export const CustomEventDetails: typeof import("../../front/components/domain/custom/CustomEventDetails.vue")['default']
export const CustomGalerie: typeof import("../../front/components/domain/custom/CustomGalerie.vue")['default']
export const CustomGreetings: typeof import("../../front/components/domain/custom/CustomGreetings.vue")['default']
export const CustomNotice: typeof import("../../front/components/domain/custom/CustomNotice.vue")['default']
export const CustomOrganizers: typeof import("../../front/components/domain/custom/CustomOrganizers.vue")['default']
export const CustomPreview: typeof import("../../front/components/domain/custom/CustomPreview.vue")['default']
export const ViewInvitation: typeof import("../../front/components/domain/view/ViewInvitation.vue")['default']
export const NuxtWelcome: typeof import("../../front/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../front/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../front/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../front/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../../front/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../front/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAccordion: typeof import("../../front/components/ui/Accordion.vue")['default']
export const LazyAddress: typeof import("../../front/components/ui/Address.vue")['default']
export const LazyButton: typeof import("../../front/components/ui/Button.vue")['default']
export const LazyCheckBox: typeof import("../../front/components/ui/CheckBox.vue")['default']
export const LazyContainer: typeof import("../../front/components/ui/Container.vue")['default']
export const LazyDatePicker: typeof import("../../front/components/ui/DatePicker.vue")['default']
export const LazyDefault: typeof import("../../front/components/ui/Default.vue")['default']
export const LazyDropDown: typeof import("../../front/components/ui/DropDown.vue")['default']
export const LazyHeader: typeof import("../../front/components/ui/Header.vue")['default']
export const LazyImageGalerie: typeof import("../../front/components/ui/ImageGalerie.vue")['default']
export const LazyImageUploader: typeof import("../../front/components/ui/ImageUploader.vue")['default']
export const LazyInputForm: typeof import("../../front/components/ui/InputForm.vue")['default']
export const LazyInputFormItem: typeof import("../../front/components/ui/InputFormItem.vue")['default']
export const LazyMap: typeof import("../../front/components/ui/Map.vue")['default']
export const LazyModal: typeof import("../../front/components/ui/Modal.vue")['default']
export const LazyRadio: typeof import("../../front/components/ui/Radio.vue")['default']
export const LazyTable: typeof import("../../front/components/ui/Table.vue")['default']
export const LazyTableContainer: typeof import("../../front/components/ui/TableContainer.vue")['default']
export const LazyTableItem: typeof import("../../front/components/ui/TableItem.vue")['default']
export const LazyText: typeof import("../../front/components/ui/Text.vue")['default']
export const LazyTextArea: typeof import("../../front/components/ui/TextArea.vue")['default']
export const LazyTip: typeof import("../../front/components/ui/Tip.vue")['default']
export const LazyAdminInvitationList: typeof import("../../front/components/domain/admin/AdminInvitationList.vue")['default']
export const LazyCustomBankDetails: typeof import("../../front/components/domain/custom/CustomBankDetails.vue")['default']
export const LazyCustomClosings: typeof import("../../front/components/domain/custom/CustomClosings.vue")['default']
export const LazyCustomContact: typeof import("../../front/components/domain/custom/CustomContact.vue")['default']
export const LazyCustomDesign: typeof import("../../front/components/domain/custom/CustomDesign.vue")['default']
export const LazyCustomEventDetails: typeof import("../../front/components/domain/custom/CustomEventDetails.vue")['default']
export const LazyCustomGalerie: typeof import("../../front/components/domain/custom/CustomGalerie.vue")['default']
export const LazyCustomGreetings: typeof import("../../front/components/domain/custom/CustomGreetings.vue")['default']
export const LazyCustomNotice: typeof import("../../front/components/domain/custom/CustomNotice.vue")['default']
export const LazyCustomOrganizers: typeof import("../../front/components/domain/custom/CustomOrganizers.vue")['default']
export const LazyCustomPreview: typeof import("../../front/components/domain/custom/CustomPreview.vue")['default']
export const LazyViewInvitation: typeof import("../../front/components/domain/view/ViewInvitation.vue")['default']
export const LazyNuxtWelcome: typeof import("../../front/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../front/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../front/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../front/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../../front/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../front/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../front/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../front/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
