
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Accordion': typeof import("../components/ui/Accordion.vue")['default']
    'Address': typeof import("../components/ui/Address.vue")['default']
    'Button': typeof import("../components/ui/Button.vue")['default']
    'CheckBox': typeof import("../components/ui/CheckBox.vue")['default']
    'Container': typeof import("../components/ui/Container.vue")['default']
    'DatePicker': typeof import("../components/ui/DatePicker.vue")['default']
    'Default': typeof import("../components/ui/Default.vue")['default']
    'DropDown': typeof import("../components/ui/DropDown.vue")['default']
    'FileUploader': typeof import("../components/ui/FileUploader.vue")['default']
    'Header': typeof import("../components/ui/Header.vue")['default']
    'InputForm': typeof import("../components/ui/InputForm.vue")['default']
    'InputFormItem': typeof import("../components/ui/InputFormItem.vue")['default']
    'Modal': typeof import("../components/ui/Modal.vue")['default']
    'Radio': typeof import("../components/ui/Radio.vue")['default']
    'Text': typeof import("../components/ui/Text.vue")['default']
    'TextArea': typeof import("../components/ui/TextArea.vue")['default']
    'Tip': typeof import("../components/ui/Tip.vue")['default']
    'CustomBankDetails': typeof import("../components/domain/custom/CustomBankDetails.vue")['default']
    'CustomClosings': typeof import("../components/domain/custom/CustomClosings.vue")['default']
    'CustomContact': typeof import("../components/domain/custom/CustomContact.vue")['default']
    'CustomDesign': typeof import("../components/domain/custom/CustomDesign.vue")['default']
    'CustomEventDetails': typeof import("../components/domain/custom/CustomEventDetails.vue")['default']
    'CustomGalerie': typeof import("../components/domain/custom/CustomGalerie.vue")['default']
    'CustomGreetings': typeof import("../components/domain/custom/CustomGreetings.vue")['default']
    'CustomNotice': typeof import("../components/domain/custom/CustomNotice.vue")['default']
    'CustomOrganizers': typeof import("../components/domain/custom/CustomOrganizers.vue")['default']
    'CustomPreview': typeof import("../components/domain/custom/CustomPreview.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAccordion': typeof import("../components/ui/Accordion.vue")['default']
    'LazyAddress': typeof import("../components/ui/Address.vue")['default']
    'LazyButton': typeof import("../components/ui/Button.vue")['default']
    'LazyCheckBox': typeof import("../components/ui/CheckBox.vue")['default']
    'LazyContainer': typeof import("../components/ui/Container.vue")['default']
    'LazyDatePicker': typeof import("../components/ui/DatePicker.vue")['default']
    'LazyDefault': typeof import("../components/ui/Default.vue")['default']
    'LazyDropDown': typeof import("../components/ui/DropDown.vue")['default']
    'LazyFileUploader': typeof import("../components/ui/FileUploader.vue")['default']
    'LazyHeader': typeof import("../components/ui/Header.vue")['default']
    'LazyInputForm': typeof import("../components/ui/InputForm.vue")['default']
    'LazyInputFormItem': typeof import("../components/ui/InputFormItem.vue")['default']
    'LazyModal': typeof import("../components/ui/Modal.vue")['default']
    'LazyRadio': typeof import("../components/ui/Radio.vue")['default']
    'LazyText': typeof import("../components/ui/Text.vue")['default']
    'LazyTextArea': typeof import("../components/ui/TextArea.vue")['default']
    'LazyTip': typeof import("../components/ui/Tip.vue")['default']
    'LazyCustomBankDetails': typeof import("../components/domain/custom/CustomBankDetails.vue")['default']
    'LazyCustomClosings': typeof import("../components/domain/custom/CustomClosings.vue")['default']
    'LazyCustomContact': typeof import("../components/domain/custom/CustomContact.vue")['default']
    'LazyCustomDesign': typeof import("../components/domain/custom/CustomDesign.vue")['default']
    'LazyCustomEventDetails': typeof import("../components/domain/custom/CustomEventDetails.vue")['default']
    'LazyCustomGalerie': typeof import("../components/domain/custom/CustomGalerie.vue")['default']
    'LazyCustomGreetings': typeof import("../components/domain/custom/CustomGreetings.vue")['default']
    'LazyCustomNotice': typeof import("../components/domain/custom/CustomNotice.vue")['default']
    'LazyCustomOrganizers': typeof import("../components/domain/custom/CustomOrganizers.vue")['default']
    'LazyCustomPreview': typeof import("../components/domain/custom/CustomPreview.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Accordion: typeof import("../components/ui/Accordion.vue")['default']
export const Address: typeof import("../components/ui/Address.vue")['default']
export const Button: typeof import("../components/ui/Button.vue")['default']
export const CheckBox: typeof import("../components/ui/CheckBox.vue")['default']
export const Container: typeof import("../components/ui/Container.vue")['default']
export const DatePicker: typeof import("../components/ui/DatePicker.vue")['default']
export const Default: typeof import("../components/ui/Default.vue")['default']
export const DropDown: typeof import("../components/ui/DropDown.vue")['default']
export const FileUploader: typeof import("../components/ui/FileUploader.vue")['default']
export const Header: typeof import("../components/ui/Header.vue")['default']
export const InputForm: typeof import("../components/ui/InputForm.vue")['default']
export const InputFormItem: typeof import("../components/ui/InputFormItem.vue")['default']
export const Modal: typeof import("../components/ui/Modal.vue")['default']
export const Radio: typeof import("../components/ui/Radio.vue")['default']
export const Text: typeof import("../components/ui/Text.vue")['default']
export const TextArea: typeof import("../components/ui/TextArea.vue")['default']
export const Tip: typeof import("../components/ui/Tip.vue")['default']
export const CustomBankDetails: typeof import("../components/domain/custom/CustomBankDetails.vue")['default']
export const CustomClosings: typeof import("../components/domain/custom/CustomClosings.vue")['default']
export const CustomContact: typeof import("../components/domain/custom/CustomContact.vue")['default']
export const CustomDesign: typeof import("../components/domain/custom/CustomDesign.vue")['default']
export const CustomEventDetails: typeof import("../components/domain/custom/CustomEventDetails.vue")['default']
export const CustomGalerie: typeof import("../components/domain/custom/CustomGalerie.vue")['default']
export const CustomGreetings: typeof import("../components/domain/custom/CustomGreetings.vue")['default']
export const CustomNotice: typeof import("../components/domain/custom/CustomNotice.vue")['default']
export const CustomOrganizers: typeof import("../components/domain/custom/CustomOrganizers.vue")['default']
export const CustomPreview: typeof import("../components/domain/custom/CustomPreview.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAccordion: typeof import("../components/ui/Accordion.vue")['default']
export const LazyAddress: typeof import("../components/ui/Address.vue")['default']
export const LazyButton: typeof import("../components/ui/Button.vue")['default']
export const LazyCheckBox: typeof import("../components/ui/CheckBox.vue")['default']
export const LazyContainer: typeof import("../components/ui/Container.vue")['default']
export const LazyDatePicker: typeof import("../components/ui/DatePicker.vue")['default']
export const LazyDefault: typeof import("../components/ui/Default.vue")['default']
export const LazyDropDown: typeof import("../components/ui/DropDown.vue")['default']
export const LazyFileUploader: typeof import("../components/ui/FileUploader.vue")['default']
export const LazyHeader: typeof import("../components/ui/Header.vue")['default']
export const LazyInputForm: typeof import("../components/ui/InputForm.vue")['default']
export const LazyInputFormItem: typeof import("../components/ui/InputFormItem.vue")['default']
export const LazyModal: typeof import("../components/ui/Modal.vue")['default']
export const LazyRadio: typeof import("../components/ui/Radio.vue")['default']
export const LazyText: typeof import("../components/ui/Text.vue")['default']
export const LazyTextArea: typeof import("../components/ui/TextArea.vue")['default']
export const LazyTip: typeof import("../components/ui/Tip.vue")['default']
export const LazyCustomBankDetails: typeof import("../components/domain/custom/CustomBankDetails.vue")['default']
export const LazyCustomClosings: typeof import("../components/domain/custom/CustomClosings.vue")['default']
export const LazyCustomContact: typeof import("../components/domain/custom/CustomContact.vue")['default']
export const LazyCustomDesign: typeof import("../components/domain/custom/CustomDesign.vue")['default']
export const LazyCustomEventDetails: typeof import("../components/domain/custom/CustomEventDetails.vue")['default']
export const LazyCustomGalerie: typeof import("../components/domain/custom/CustomGalerie.vue")['default']
export const LazyCustomGreetings: typeof import("../components/domain/custom/CustomGreetings.vue")['default']
export const LazyCustomNotice: typeof import("../components/domain/custom/CustomNotice.vue")['default']
export const LazyCustomOrganizers: typeof import("../components/domain/custom/CustomOrganizers.vue")['default']
export const LazyCustomPreview: typeof import("../components/domain/custom/CustomPreview.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
